In [1]:
import numpy as np

In [4]:
X = np.random.multivariate_normal(mean = [0, 2, 4],
                                  cov = [[1,0,0],[0,1,0],[0,0,1]],
                                  size = 1000)
Y = np.random.choice([1,2],size = 1000, replace = True)

In [9]:
dist = np.power(X[:,None] - X,2).sum(axis=2)

In [10]:
dist.shape

(1000, 1000)

In [11]:
dist

array([[0.        , 2.65071298, 0.63184638, ..., 3.18795959, 3.55844177,
        1.35824012],
       [2.65071298, 0.        , 0.91983757, ..., 0.18141649, 5.01647873,
        2.23512708],
       [0.63184638, 0.91983757, 0.        , ..., 1.55270439, 3.91882817,
        0.53203485],
       ...,
       [3.18795959, 0.18141649, 1.55270439, ..., 0.        , 4.70117679,
        3.44249138],
       [3.55844177, 5.01647873, 3.91882817, ..., 4.70117679, 0.        ,
        5.11091292],
       [1.35824012, 2.23512708, 0.53203485, ..., 3.44249138, 5.11091292,
        0.        ]])

In [30]:
dist

array([[0.        , 2.65071298, 0.63184638, ..., 3.18795959, 3.55844177,
        1.35824012],
       [2.65071298, 0.        , 0.91983757, ..., 0.18141649, 5.01647873,
        2.23512708],
       [0.63184638, 0.91983757, 0.        , ..., 1.55270439, 3.91882817,
        0.53203485],
       ...,
       [3.18795959, 0.18141649, 1.55270439, ..., 0.        , 4.70117679,
        3.44249138],
       [3.55844177, 5.01647873, 3.91882817, ..., 4.70117679, 0.        ,
        5.11091292],
       [1.35824012, 2.23512708, 0.53203485, ..., 3.44249138, 5.11091292,
        0.        ]])

In [42]:
trya = Y[np.argsort(dist,axis =1 )]

In [60]:
aa = trya[:,:5]

In [74]:
aa.shape

(1000, 5)

In [72]:
np.unique(aa, axis = 1, return_counts=True)

(array([[1, 1, 1, 2, 2],
        [2, 2, 2, 1, 2],
        [1, 1, 2, 1, 2],
        ...,
        [2, 2, 1, 1, 1],
        [2, 2, 1, 1, 2],
        [1, 2, 2, 1, 2]]),
 array([1, 1, 1, 1, 1]))